apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata: 
      labels:
        app: accounts
    spec: 
      containers:
        - name: accounts
          image: robindocker/microservice_accounts:1.0.0
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef: 
                name: microservicios-configmap
                key: spring_profiles_active
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef: 
                name: microservicios-configmap
                key: spring_config_config_import  
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef: 
                name: microservicios-configmap
                key: eureka_client_serviceurl_defaultzone  
             
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
